@startuml
skinparam shadowing false

start
:Вхід у веб-застосунок;
if (JWT токен присутній у LocalStorage?) then (так)
  :Авторизація успішна;
else (ні)
  repeat
    :Показати сторінку Входу / Реєстрації;
    :Користувач вводить email та пароль;
    :Надіслати POST-запит авторизації;
  backward:Відобразити повідомлення про помилку;
  repeat while (Дані авторизації коректні?) is (ні) not (так)
  :Зберегти отриманий токен у LocalStorage;
endif

:Перенаправлення на Головну сторінку (Дашборд);

repeat
  :Очікування вибору дії від користувача;
  if (Вибрана дія?) then (Додавання підписки)
    :Відкрити форму додавання;
    :Ввести назву, вартість, валюту, дату списання;
    :Натиснути "Зберегти";
    :Відправити POST-запит на створення підписки;
    :Оновити стан та перерахувати витрати;
  else if (Вибрана дія?) then (Редагування / Архівування)
    :Обрати підписку в списку;
    if (Тип операції?) then (Редагування)
      :Змінити поля підписки у формі;
      :Надіслати PUT-запит на сервер;
    else (Архівування)
      :Надіслати PATCH-запит (isArchived = true);
    endif
    :Оновити стан інтерфейсу;
  else if (Вибрана дія?) then (Перегляд аналітики)
    :Відобразити кругову діаграму витрат за категоріями;
    :Відобразити стовпчикову діаграму прогнозу на рік;
  else (Вихід із системи)
    :Очистити JWT токен з LocalStorage;
    :Перенаправити на сторінку входу;
    stop
  endif
repeat while (Користувач залишається авторизованим)

stop
@enduml
